// Extracted and curated master parts catalogue from topsalesitems document
export interface TopSalesItem {
  p: string; // Part Number
  d: string; // Description
  c?: string; // Category
}

export const TOP_SALES_ITEMS: TopSalesItem[] = [
  // Page 1
  { p: "HLA 5637-24V/01305", d: "AUTO BULB", c: "Electrical & Lighting" },
  { p: "L 0205-1NQ ORG", d: "AUTO STICKER SMALL", c: "Body & Safety" },
  { p: "L 0205-2NQ JPN", d: "AUTO STICKER SMALL", c: "Body & Safety" },
  { p: "L 0190", d: "ELECTRIC TAPE JAPAN", c: "Electrical & Lighting" },
  { p: "YSN/DFT ESV 2811A", d: "EXHAUST SPRING VOLVO FH", c: "Hardware & Fittings" },
  { p: "HLA 7511-24V/01381", d: "AUTO BULB", c: "Electrical & Lighting" },
  { p: "SMX/AZ 640C/A", d: "LED SIDE LIGHT YELLOW", c: "Electrical & Lighting" },
  { p: "SDPL 0109975982", d: "PVC PIPE 12MM", c: "Pipes & Hoses" },
  { p: "L 0210-2NQ JPN", d: "AUTO STICKER MEDIUM", c: "Body & Safety" },
  { p: "L 0210-1NQ ORG", d: "AUTO STICKER MEDIUM", c: "Body & Safety" },
  { p: "DFT 0004010672", d: "COLLER NUT (32N F/T)", c: "Hardware & Fasteners" },
  { p: "YORK M00/6659", d: "HOSE CLIP", c: "Hardware & Fittings" },
  { p: "GN GREASE NIPPLE MIX", d: "GREASE NIPPLE MIX", c: "Hardware & Fittings" },
  { p: "HLA 64215-24V", d: "H-7 BULB", c: "Electrical & Lighting" },
  { p: "UN TRANSIT SMALL", d: "TRANSIT STICKER 20*20", c: "Body & Safety" },
  { p: "SHELL 20W 50 R2", d: "SHELL 20W 50 DIESEL OIL 3*5", c: "Filters & Lubricants" },
  { p: "CNGR 0049890420/20L", d: "AD BLUE 20L", c: "Fluids & Chemicals" },
  { p: "AH 408/AZ 925", d: "NUMBER PLATE LIGHT", c: "Electrical & Lighting" },
  { p: "HLA 7537-24V/03382", d: "AUTO BULB", c: "Electrical & Lighting" },
  { p: "YORK 0/6661", d: "HOSE CLIP", c: "Hardware & Fittings" },
  { p: "BSH 5637/1987302510", d: "AUTO BULB", c: "Electrical & Lighting" },
  { p: "L 5269", d: "WATER TAPLON TAPE", c: "Hardware & Fittings" },
  { p: "DFT UML 1631", d: "BRAKE SHOE RIVET ROR", c: "Brakes & Air Systems" },
  { p: "L FDD2-250BL", d: "HORN CLIP", c: "Electrical & Lighting" },
  { p: "DFT UUE 259", d: "BATTERY TERMINAL (+VE)", c: "Electrical & Lighting" },
  { p: "YORK 000/6658", d: "HOSE CLIP", c: "Hardware & Fittings" },
  { p: "DFT UUB 316", d: "REDUCER 16*22*1.5", c: "Hardware & Fittings" },
  { p: "DFT UUE 260", d: "BATTERY TERMINAL (-VE)", c: "Electrical & Lighting" },
  { p: "DFT 0005455111", d: "PUSH AND PULL SWITCH", c: "Electrical & Lighting" },
  { p: "VOLVO 15W 40", d: "VOLVO 15W 40 DIESEL OIL 20L", c: "Filters & Lubricants" },
  { p: "L FUSE EXT BIG MIX", d: "FUSE EXT BIG MIX", c: "Electrical & Lighting" },
  { p: "SK/DFT 1137/6.52808", d: "STRAIGHT AUTO FITTING PLASTIC 8MM", c: "Hardware & Fittings" },

  // Page 2
  { p: "L EM 14361", d: "EMERGENCY STICKER SMALL", c: "Body & Safety" },
  { p: "AH 1137Y", d: "12 LED SIDE LIGHT YELLOW", c: "Electrical & Lighting" },
  { p: "DFT 659112612", d: "WHEEL BOLT", c: "Hardware & Fasteners" },
  { p: "SK/DFT 0029906171", d: "FITTING MANUAL 12MM", c: "Hardware & Fittings" },
  { p: "L 0153", d: "COLOUR COTTON RAGS", c: "Hardware & Fittings" },
  { p: "L TR UUH 5540B", d: "TYRE VALVE SMALL", c: "Hardware & Fittings" },
  { p: "RKN MD 069782", d: "OIL FILTER MITSUBISHI O/M", c: "Filters & Lubricants" },
  { p: "SK/DFT 1136/6.52806", d: "STRAIGHT AUTO FITTING PLASTIC 6MM", c: "Hardware & Fittings" },
  { p: "YORK 00/6660", d: "HOSE CLIP", c: "Hardware & Fittings" },
  { p: "DFT 915011010102", d: "BENJO BOLT 16MM", c: "Hardware & Fittings" },
  { p: "AZ/DC 2027L", d: "LED STOP LIGHT (3 CHAMBER)", c: "Electrical & Lighting" },
  { p: "SK/DFT 0089976082", d: "PVC PIPE 6MM", c: "Pipes & Hoses" },
  { p: "AZ 372C", d: "NUMBER PLATE LIGHT (LED)", c: "Electrical & Lighting" },
  { p: "L 12536/8861-2 JPN", d: "LONG VEHICLE STICKER JAPAN", c: "Body & Safety" },
  { p: "DFT 074304016200", d: "BOOSTER NIPPLE 12MM", c: "Hardware & Fittings" },
  { p: "UVSL 68 H", d: "UNIVERSAL 68 HYDRAULIC OIL 20L", c: "Filters & Lubricants" },
  { p: "AZ 650", d: "WIPER BLADE", c: "Body & Safety" },
  { p: "HLA 2845-24V", d: "ALL GLASS BULB SMALL", c: "Electrical & Lighting" },
  { p: "L 2841-24V", d: "ALL GLASS BULB", c: "Electrical & Lighting" },
  { p: "DC 2960", d: "FLASH LIGHT 12/24V", c: "Electrical & Lighting" },
  { p: "DFT UUE 249Z", d: "7 CORE WIRE", c: "Electrical & Lighting" },
  { p: "AZST 8862 2ND JPN", d: "STICKER 80 SPEED", c: "Body & Safety" },
  { p: "SHELL 20W50 ROTELA", d: "SHELL 20W50 DIESEL OIL 6*5", c: "Filters & Lubricants" },
  { p: "ADNOC 20W 50 6*5", d: "ADNOC 20W 50 DIESEL OIL HPSD", c: "Filters & Lubricants" },
  { p: "HG H200W10", d: "HG H200W10 OIL FILTER", c: "Filters & Lubricants" },
  { p: "DFT UUB 1763", d: "BOOSTER NIPPLE 16*12.5", c: "Hardware & Fittings" },
  { p: "4362-2NQ JPN", d: "KEEP DISTANCE STICKER RED/BLACK", c: "Body & Safety" },
  { p: "DFT 0980623220", d: "BPW HUB BOLT N/M", c: "Hardware & Fasteners" },
  { p: "ST H200W10", d: "ST H200W10 OIL FILTER", c: "Filters & Lubricants" },
  { p: "YORK 0X/6662", d: "HOSE CLIP", c: "Hardware & Fittings" },
  { p: "CNGR RC 4L", d: "CNGR RADIATOR COOLANT 4*4", c: "Fluids & Chemicals" },
  { p: "SDPL UME 2677YLZ", d: "LED SIDE LIGHT YELLOW", c: "Electrical & Lighting" },
  { p: "DFT DAF 1139", d: "STRAIGHT AUTO FITTING PLASTIC 12MM", c: "Hardware & Fittings" },
  { p: "SDPL UUE 5582Z(YL)", d: "LED SIDE LIGHT YELLOW", c: "Electrical & Lighting" },

  // Page 3
  { p: "BF/SDPL 20398660", d: "INDICATOR LIGHT FH", c: "Electrical & Lighting" },
  { p: "VOLVO 15W40 5L", d: "VOLVO 15W 40 DIESEL OIL 3*5", c: "Filters & Lubricants" },
  { p: "AZ 301B", d: "SEAT BELT AUTOMATIC", c: "Body & Safety" },
  { p: "DFT 915011008103", d: "BENJO BOLT 14MM", c: "Hardware & Fittings" },
  { p: "SK/DFT 0019970652", d: "PVC PIPE 10MM", c: "Pipes & Hoses" },
  { p: "DFT UUE 249", d: "7 CORE WIRE", c: "Electrical & Lighting" },
  { p: "L 16919", d: "SEAT BELT STICKER 15*10CM", c: "Body & Safety" },
  { p: "L 074310013002", d: "BOOSTER HOSE", c: "Pipes & Hoses" },
  { p: "L SPONSE", d: "REAR DOOR SPONGE", c: "Body & Safety" },
  { p: "DFT 314B", d: "BENJO EYE", c: "Hardware & Fittings" },
  { p: "SND/TWD 0004010672", d: "COLLER NUT (32N F/T)", c: "Hardware & Fasteners" },
  { p: "RKN 90915-YZZD4", d: "OIL FILTER LAND CRUISER/HIACE", c: "Filters & Lubricants" },
  { p: "SK/SDPL 0089979082", d: "PVC PIPE 8MM", c: "Pipes & Hoses" },
  { p: "DFT 007603016103", d: "COPPER WASHER 16MM", c: "Hardware & Fittings" },
  { p: "L 9305", d: "DANGER STICKER MEDIUM", c: "Body & Safety" },
  { p: "AZST 9305 2ND JPN", d: "DANGER STICKER MEDIUM", c: "Body & Safety" },
  { p: "L EM", d: "EMERGENCY NUMBERS STICKER", c: "Body & Safety" },
  { p: "AH 16MM", d: "16MM WASHER WITH RUBBER", c: "Hardware & Fittings" },
  { p: "DFT 1138/6.52810", d: "STRAIGHT AUTO FITTING PLASTIC 10MM", c: "Hardware & Fittings" },
  { p: "EP 9194510000", d: "CARGO BELT 10 METER", c: "Safety & Cargo" },
  { p: "L 4217", d: "BATTERY TERMINAL COVER BL/RED", c: "Electrical & Lighting" },
  { p: "L 9304", d: "NO SMOKING STICKER MEDIUM", c: "Body & Safety" },
  { p: "YORK 4/1953", d: "HOSE CLIP", c: "Hardware & Fittings" },
  { p: "QV 51105", d: "FIRE CYLINDER 6KG", c: "Safety & Cargo" },
  { p: "HLA 64196-24V", d: "H-4 BULB", c: "Electrical & Lighting" },
  { p: "HLA 64156-24V", d: "H-3 BULB", c: "Electrical & Lighting" },
  { p: "OE 0009894325/19", d: "OE RADIATOR COOLANT 12*1L", c: "Fluids & Chemicals" },
  { p: "AZ 759 /AH 2222", d: "REVERSE LIGHT 16 LED SQUARE", c: "Electrical & Lighting" },
  { p: "L 8862/10135", d: "STICKER 80 SPEED", c: "Body & Safety" },
  { p: "AZ 920", d: "NUMBER PLATE LIGHT (LED)", c: "Electrical & Lighting" },
  { p: "CALTEX 15W 40", d: "CALTEX 15W 40 DIESEL OIL 4*5", c: "Filters & Lubricants" },
  { p: "YORK 1/0223", d: "HOSE CLIP", c: "Hardware & Fittings" },
  { p: "DFT UML 782", d: "BRAKE SHOE RIVET", c: "Brakes & Air Systems" },
  { p: "HLA 64155", d: "H-1 BULB", c: "Electrical & Lighting" },

  // Page 4
  { p: "DFT 659112613", d: "REAR WHEEL BOLT", c: "Hardware & Fasteners" },
  { p: "AZ 6007R", d: "LED LIGHT RED", c: "Electrical & Lighting" },
  { p: "HG E422KP D98", d: "HG E422KP D98 DIESEL FILTER MAN", c: "Filters & Lubricants" },
  { p: "UN TRANSIT", d: "TRANSIT STICKER 38*40", c: "Body & Safety" },
  { p: "HG E510H07D129", d: "E510H07D129 OIL FILTER", c: "Filters & Lubricants" },
  { p: "SDPL UUE 264Z", d: "STOP LENSE 3 CHAMBER", c: "Electrical & Lighting" },
  { p: "SK/GM 0004292184", d: "AIR COUPLING RUBBER", c: "Hardware & Fittings" },
  { p: "WB 4324102227 TURKEY", d: "AIR DRYER FILTER", c: "Brakes & Air Systems" },
  { p: "DC UUG 5413", d: "AIR DUSTER KIT BLUE", c: "Hardware & Fittings" },
  { p: "L STICKER WEIGHT", d: "STICKER WEIGHT", c: "Body & Safety" },
  { p: "OE ME025153", d: "CANTER SPRING BUSH", c: "Brakes & Air Systems" },
  { p: "AZ 2850/BPV 8774", d: "DIESEL TANK CAP W/KEY MAGNET TYPE", c: "Body & Safety" },
  { p: "AZST 014SC", d: "NO SMOKING STICKER MEDIUM", c: "Body & Safety" },
  { p: "FB/DT 0109975982", d: "PVC PIPE 12MM", c: "Pipes & Hoses" },
  { p: "L 4362", d: "KEEP DISTANCE STICKER 3M ORG", c: "Body & Safety" },
  { p: "DFT UUB 688", d: "DRAIN PLUG", c: "Hardware & Fittings" },
  { p: "HG E500KP02 D36", d: "HG E500KP02 D36 DIESEL FILTER", c: "Filters & Lubricants" },
  { p: "HG E500H D129", d: "HG E500H D129 OIL FILTER", c: "Filters & Lubricants" },
  { p: "SK 999999-12/6.52812", d: "STRAIGHT AUTO FITTING PLASTIC 12MM", c: "Hardware & Fittings" },
  { p: "AZ 700", d: "WIPER BLADE", c: "Body & Safety" },
  { p: "L 8861", d: "LONG VEHICLE STICKER 3M ORG", c: "Body & Safety" },
  { p: "DFT UUB 315A", d: "BENJO EYE", c: "Hardware & Fittings" },
  { p: "DFT 0260102560", d: "COTTER PIN HUB BOLT BPW", c: "Hardware & Fasteners" },
  { p: "CALTEX 20W 50", d: "CALTEX 20W 50 DIESEL OIL 4*5", c: "Filters & Lubricants" },
  { p: "DFT UUN 1027/14*50", d: "BOLT & NUT (F/T)", c: "Hardware & Fasteners" },
  { p: "ZIC 20W50 (6000)", d: "ZIC 20W 50 DIESEL OIL (6000)", c: "Filters & Lubricants" },
  { p: "SMX BA116", d: "REVERSE HORN", c: "Electrical & Lighting" },
  { p: "YORK 3X/1414", d: "HOSE CLIP", c: "Hardware & Fittings" },
  { p: "AZ 200 B", d: "TRIANGLE BIG/ REFLECTOR", c: "Safety & Cargo" },
  { p: "SA/SK 6.52804", d: "STRAIGHT AUTO FITTING PLASTIC 4MM", c: "Hardware & Fittings" },
  { p: "SPRM MB025153", d: "CANTER SPRING BUSH", c: "Brakes & Air Systems" },
  { p: "L BA116", d: "REVERSE HORN HD", c: "Electrical & Lighting" },
  { p: "FRG 4231079000", d: "BRAKE BOOSTER TRAILER T30", c: "Brakes & Air Systems" },
  { p: "AZ 213", d: "FLASH LIGHT BRACKET TYPE", c: "Electrical & Lighting" },

  // Page 5
  { p: "AH 14MM", d: "14MM WASHER WITH RUBBER", c: "Hardware & Fittings" },
  { p: "AM 40/L 5037", d: "AM 40", c: "Fluids & Chemicals" },
  { p: "EP G 1KG", d: "EP GREASE 1KG", c: "Filters & Lubricants" },
  { p: "ST H200WN01", d: "OIL FILTER VOLVO BIG HOLE", c: "Filters & Lubricants" },
  { p: "SDPL UUE 252 (BLK)", d: "AUTO CABLE BLACK 21MM", c: "Electrical & Lighting" },
  { p: "L LC 0190", d: "ELECTRIC TAPE", c: "Electrical & Lighting" },
  { p: "TWD 0980623220", d: "BPW HUB BOLT N/M", c: "Hardware & Fasteners" },
  { p: "DFT 659002171", d: "REAR WHEEL CLAMP", c: "Hardware & Fasteners" },
  { p: "FAG 0210405400", d: "FAG GREASE 1KG", c: "Filters & Lubricants" },
  { p: "DFT 9424010371", d: "REAR HUB BOLT ACT.", c: "Hardware & Fasteners" },
  { p: "DFT 22*18 U.L", d: "UNION LONG", c: "Hardware & Fittings" },
  { p: "DFT 0004700405", d: "DIESEL TANK CAP ACT/FH", c: "Body & Safety" },
  { p: "ST 90915-YZZD4", d: "OIL FILTER LAND CRUISER/HIACE", c: "Filters & Lubricants" },
  { p: "YORK 2X/1314", d: "HOSE CLIP", c: "Hardware & Fittings" },
  { p: "VR 0019892920", d: "DIRKO GASKET SEALANT", c: "Fluids & Chemicals" },
  { p: "BSH 7511/1987302865", d: "AUTO BULB", c: "Electrical & Lighting" },
  { p: "YORK 1X/3040", d: "HOSE CLIP", c: "Hardware & Fittings" },
  { p: "FA 806WH", d: "FIRST AID KIT BOX SMALL", c: "Safety & Cargo" },
  { p: "BSH 0986AH0253", d: "MINI RELAY", c: "Electrical & Lighting" },
  { p: "L 7850", d: "SILICONE WHITE/BLACK", c: "Fluids & Chemicals" },
  { p: "AZ RVL 107/5166", d: "FLASH LIGHT SOLAR", c: "Electrical & Lighting" },
  { p: "YORK 3/1983", d: "HOSE CLIP", c: "Hardware & Fittings" },
  { p: "HG H200WN01", d: "HG H200WN01 OIL FILTER", c: "Filters & Lubricants" },
  { p: "TGR DI17.0004", d: "LED SIDE LIGHT YELLOW", c: "Electrical & Lighting" },
  { p: "BSH F002H60021", d: "BOSCH DOT4 BRAKE OIL 500ML", c: "Fluids & Chemicals" },
  { p: "RKN 90915-YZZE2", d: "OIL FILTER TOYOTA/COROLLA", c: "Filters & Lubricants" },
  { p: "AH 384", d: "GLASS BREAKER HAMMER", c: "Safety & Cargo" },
  { p: "FB 0331099010", d: "PLASTIC SEAL BP-16", c: "Hardware & Fittings" },
  { p: "YORK 1A/6663", d: "HOSE CLIP", c: "Hardware & Fittings" },
  { p: "HG 4324102227", d: "AIR DRYER FILTER", c: "Brakes & Air Systems" },
  { p: "HG E197H D23", d: "HG E197H D23 OIL FILTER", c: "Filters & Lubricants" },
  { p: "BP 20W 50 4*5", d: "BP 20W 50 DIESEL OIL 4*5", c: "Filters & Lubricants" },
  { p: "TEMBY/AZ 452", d: "CANTER STOP LENSE", c: "Electrical & Lighting" },
  { p: "FB 0331099020", d: "PLASTIC SEAL BP-16", c: "Hardware & Fittings" }
];
